### ISSUE TITLE
update feature matrix informations into djangopackages

### ISSUE THREAD

**Issue by luzfcb** [benjaoming/django-nyt#15]
Hello, someone who knows more than I of this project, please, update the follow page and include some feature that is interesting to differentiate it from other projects

https://www.djangopackages.com/grids/g/notification/

**Comment by benjaoming** [comment]
I had a look, but I'm missing editing features on the page. I added a link to the docs.

If possible, you can add that this project is:

 * In beta, not alpha
 * Uses django signals (this is important: django-nyt does not aim to include all kinds of message APIs, rather it's just very simple to extend)

**Comment by benjaoming** [comment]
And thanks for referring!

**Comment by luzfcb** [comment]
it is in beta, so it is necessary to modify in https://github.com/benjaoming/django-nyt/blob/master/setup.py#L53

**Comment by benjaoming** [comment]
Ah, thanks, will be noted in the next pypi release then. 7166e18

**Comment by benjaoming** [comment]
Updated somewhat, not sure I think the feature matrix is very nicely done or makes the choice very obvious, but whatever, I'll try to make a proper description in our docs, saying why django-nyt should be the preferred choice for all :)
