### ISSUE TITLE
"templates/notification_email_message.txt" throws a TemplateSyntaxError when notifymail command is used with Django > 1.9

### ISSUE THREAD

**Issue by VCAMP** [benjaoming/django-nyt#19]
I believe it's because of this: https://github.com/sehmaschine/django-grappelli/issues/648

Have given a quick look at the template code and I'm not sure of how {% load url from future %} is being used; might not create a problem if it's removed. Creating an alternative template without {% load url from future %} for Django > 1.9 users could be a quick fix? Will send a pull request.

**Comment by benjaoming** [comment]
Fixed in #20
