### ISSUE TITLE
A bug in filtering subscriptions in `Notification.create_notifications`

### ISSUE THREAD

**Issue by msarabi95** [benjaoming/django-nyt#22]
On line 242 in models.py:
https://github.com/benjaoming/django-nyt/blob/master/django_nyt/models.py#L242

When creating notifications of a specific `NotificationType`, subscriptions to that `NotificationType` with an empty `object_id` will not receive any notifications.

The reasons seems to be that the above-mentioned line is filtering these subscriptions out. `Subscription.object_id` is a `CharField`, and thus will have a value of `""` (not `None`) when empty.

Changing the above line to `Q(object_id="")` resolves the issue.

**Comment by msarabi95** [comment]
OK I just retried that.
It turns out to be working properly.

Sorry :)

**Comment by benjaoming** [comment]
Np, thanks for making a nice description of the issue anyways :)
