### ISSUE TITLE
Invalid group name

### ISSUE THREAD

**Issue by mizi** [benjaoming/django-nyt#29]
The last in ws_disconnect causes the following exception:

> TypeError: Group name must be a valid unicode string containing only alphanumerics, hyphens, or periods.

because settings.NOTIFICATION_CHANNEL is a format string.

I think this line isn't needed and was left there by mistake in 251bfc0

```python
@channel_session_user
def ws_disconnect(message):
    """
    Connected to websocket.disconnect
    """
    logger.debug("Removing connection for user {} (disconnect)".format(message.user))
    for subscription in models.Subscription.objects.filter(settings__user=message.user):
        Group(
            settings.NOTIFICATION_CHANNEL.format(
                notification_key=subscription.notification_type.key
            )
        ).discard(message.reply_channel)
    Group(settings.NOTIFICATION_CHANNEL).discard(message.reply_channel)
```

**Comment by benjaoming** [comment]
The group is supposed to contain the notification key such that people can subscribe to only specific channels (notifications).

That should be fine, however there could be an issue with your notification key - could we somehow allow notification keys that don't conform to `only alphanumerics, hyphens, or periods.` ?

**Comment by ztomaz** [comment]
The problem is the second Group(...).discard function:
Group(settings.NOTIFICATION_CHANNEL).discard(message.reply_channel), because it uses non formated  settings.NOTIFICATION_CHANNEL (value is: "nyt_all-{notification_key:s}") which contains non allowed characters. I also think it was left there by mistake

**Comment by benjaoming** [comment]
I totally missed the point in this issue, thanks @ztomaz :)

**Comment by mizi** [comment]
Thanks @benjaoming, thanks @ztomaz :)
