### ISSUE TITLE
Notifications not pushed onto sockets

### ISSUE THREAD

**Issue by timeyyy** [benjaoming/django-nyt#39]
Latest pre release 1.0b5

Notifications will come through on page refresh, but will not come in realtime

**Comment by timeyyy** [comment]
it was my error

**Comment by ahmadhaidarahmad** [comment]
Why notifications can't be polled on realtime from server side using group.send i'm having this issue also if u can help me please

**Comment by benjaoming** [comment]
@ahmadhaidarahmad please don't ask questions in a random closed issue
