### ISSUE TITLE
Group.send not working in realtime in django-nyt

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [benjaoming/django-nyt#48]
I changed the channels backend to redis server and when trying to poll a group.send from python it doesn't work in real time only works on page refresh and on socket.send from javascript any help please to let notifications show in realtime for users

**Comment by benjaoming** [comment]
Hi @ahmadhaidarahmad - I'm sorry that you are having problems with your Redis setup.

You can't just say that something isn't working without providing the proper information to fix the issue. If there even is one.

It sounds like you should read up about django-channels and try to get the fundamental pieces working. If there is a specific issue in django-nyt, please report it here, outlining any tracebacks or wrongful behavior that you find.

http://channels.readthedocs.io/en/latest/

**Comment by ahmadhaidarahmad** [comment]
Hi @benjaoming  thank you for your response .i previously set django with channels and tried when i called the group(groupname).send from django view and from shell the ws-receive consumer worked properly and returned the sent data and the websocket  on the browser acted  when caling the group.send 
But when i tried this with django nyt it didn't respond at realtime eventhough when trying to call group.send from python view and python shell knowing that the group name is true if you help me with this or just let me try it in a real time mode with an example . Very gratefull for you and sorry for taking your time

**Comment by benjaoming** [comment]
There's an example app here: https://github.com/benjaoming/django-nyt/tree/master/test-project

**Comment by ahmadhaidarahmad** [comment]
@benjaoming thank you a lot for your help i appreciate that i will try it
