### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'AnonymousUser'

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [benjaoming/django-nyt#50]
Hi @benjaoming  I'm working on the test project from the link you gave to me I'm getting this error in this line "C:\Python27\lib\site-packages\django_nyt\consumers.py", line 23, in ws_connect
    for subscription in models.Subscription.objects.filter(settings__user=message.user):
Does this effect the Group.send and doesn't make connection to websocket work properly ? can you help me in this please

**Comment by ahmadhaidarahmad** [comment]
Thank you @benjaoming  that solved the whole problem and now it working perfectly with real time

**Comment by benjaoming** [comment]
It's released as 1.0b6
